### ISSUE TITLE
Feature request - add some mortality ratios to the front tables

### ISSUE THREAD

**Issue by ewildgoose** [code-shoily/covid19#13]
The data is fascinating to see right now. Either there is something wrong with the numbers of say Mexico vs USA, or it's showing a HUGE difference in mortality/recovery? The deaths vs cases is just staggeringly different between them?

I suspect a line graph of some of these statistics would be super interesting as well (per country). I realise there is a long lead time between the mortality number and say the case numbers, but perhaps one could apply some (documented) offset for the sake of charting a recovery/mortality ratio line? I think we would see significant peaks and falls as the levels of virus ebb and return. I would be curious to see if there is an "elbow" where the shape of the graph suddenly climbs, eg once levels reach some high point, deaths tend to spike upwards as hospitals become overwhelmed?

I hope this isn't too ghoulish... Interesting times

**Comment by code-shoily** [comment]
I will work on these in the long weekend. I actually focused on building the framework and learning the stack without looking into the dataset much (which is why I didn't upload it anywhere or added it in hex ;) ). And my sense of data visualization is really, really bad so your suggestions here are valuable. I will try to add the features you asked for :)
